data_paths:
  raw_data: "./data/raw/corpus.jsonl"
  processed_data: "./data/processed/"
  embeddings_store: "./vector_db/"

model_settings:
  embedding_model: "all-MiniLM-L6-v2"
  vector_db: "Qdrant"
  batch_size: 32

Qdrant:
  url: "http://localhost:6333"
  collection_name: "retriever_v0"


runtime:
  debug: False
  num_workers: 4
